services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge
 
 